import numpy as np
import matplotlib.pylab as plt

tiempo=np.genfromtxt("data_posiciones.dat",usecols=(0))
U1=np.genfromtxt("data_posiciones.dat",usecols=(1))
U2=np.genfromtxt("data_posiciones.dat",usecols=(2))
U3=np.genfromtxt("data_posiciones.dat",usecols=(3))

U1_07=np.genfromtxt("data_posiciones_07.dat",usecols=(1))
U2_07=np.genfromtxt("data_posiciones_07.dat",usecols=(2))
U3_07=np.genfromtxt("data_posiciones_07.dat",usecols=(3))

U1_35=np.genfromtxt("data_posiciones_35.dat",usecols=(1))
U2_35=np.genfromtxt("data_posiciones_35.dat",usecols=(2))
U3_35=np.genfromtxt("data_posiciones_35.dat",usecols=(3))

U1_gamma02=np.genfromtxt("data_posiciones_gamma02.dat",usecols=(1))
U2_gamma02=np.genfromtxt("data_posiciones_gamma02.dat",usecols=(2))
U3_gamma02=np.genfromtxt("data_posiciones_gamma02.dat",usecols=(3))

U1_gamma07=np.genfromtxt("data_posiciones_gamma07.dat",usecols=(1))
U2_gamma07=np.genfromtxt("data_posiciones_gamma07.dat",usecols=(2))
U3_gamma07=np.genfromtxt("data_posiciones_gamma07.dat",usecols=(3))

U1_1=np.genfromtxt("data_posiciones1.dat",usecols=(1))
U2_1=np.genfromtxt("data_posiciones1.dat",usecols=(2))
U3_1=np.genfromtxt("data_posiciones1.dat",usecols=(3))

U1_2=np.genfromtxt("data_posiciones2.dat",usecols=(1))
U2_2=np.genfromtxt("data_posiciones2.dat",usecols=(2))
U3_2=np.genfromtxt("data_posiciones2.dat",usecols=(3))




plt.figure()
plt.plot(tiempo,U1, c="royalblue", label="primer piso", linewidth=0.7)
plt.plot(tiempo,U2, c="lawngreen", label="segundo piso", linewidth=0.7)
plt.plot(tiempo,U3, c="tomato", label="tercer piso", linewidth=0.7)
plt.xlabel("tiempo")
plt.ylabel("desplazamiento horizontal")
plt.title("Desplazamiento hotizontal vs. Tiempo")
plt.legend()
plt.grid()
plt.savefig("Desplazamiento.pdf")
plt.close()

omegas=np.genfromtxt("maximo_movimiento.dat",usecols=(0))
U1_max=np.genfromtxt("maximo_movimiento.dat",usecols=(1))
U2_max=np.genfromtxt("maximo_movimiento.dat",usecols=(2))
U3_max=np.genfromtxt("maximo_movimiento.dat",usecols=(3))


plt.figure()
plt.plot(omegas,U1_max, c="g", label="primer piso", linewidth=0.7 )
plt.plot(omegas,U2_max, c="magenta", label="segundo piso", linewidth=0.7)
plt.plot(omegas,U3_max, c="c", label="tercer piso", linewidth=0.7 )
plt.xlabel("Omegas")
plt.ylabel("desplazamiento horizontal")
plt.title("Max. Desplazamiento hotizontal vs. omegas")
plt.legend()
plt.grid()
plt.savefig("Desplazamiento_omegas.pdf")
plt.close()

plt.figure(figsize=[10,10])
plt.subplot(3,1,1)
plt.title('Resonancia: primer piso')
plt.plot(tiempo,U1, c="g", label="omega=1", linewidth=0.7 )
plt.plot(tiempo,U1_07, c="magenta", label="omega=0.7", linewidth=0.7)
plt.plot(tiempo,U1_35, c="c", label="omega=3.5", linewidth=0.7 )
plt.grid()
plt.legend()
plt.subplot(3,1,2)
plt.title('Resonancia:segundo piso')
plt.plot(tiempo,U2, c="g", label="omega=1", linewidth=0.7 )
plt.plot(tiempo,U2_07, c="magenta", label="omega=0.7", linewidth=0.7)
plt.plot(tiempo,U2_35, c="c", label="omega=3.5", linewidth=0.7 )
plt.ylabel("Amplitud")
plt.grid()
plt.legend()
plt.subplot(3,1,3)
plt.title('Resonancia: tercer piso')
plt.plot(tiempo,U3, c="g", label="omega=1", linewidth=0.7 )
plt.plot(tiempo,U3_07, c="magenta", label="omega=0.7", linewidth=0.7)
plt.plot(tiempo,U3_35, c="c", label="omega=3.5", linewidth=0.7 )
plt.xlabel("Tiempo")
plt.grid()
plt.legend()
plt.savefig("resonancia.pdf")
plt.close()

plt.figure(figsize=[10,10])
plt.subplot(2,1,1)
plt.title('gamma=0,2')
plt.plot(tiempo,U1_gamma02, c="g", label="piso 1", linewidth=0.7 )
plt.plot(tiempo,U2_gamma02, c="magenta", label="piso 2", linewidth=0.7)
plt.plot(tiempo,U3_gamma02, c="c", label="piso 3", linewidth=0.7 )
plt.ylabel("Amplitud")
plt.grid()
plt.subplot(2,1,2)
plt.title('gamma=0,7')
plt.plot(tiempo,U1_gamma07, c="g", label="piso 1", linewidth=0.7 )
plt.plot(tiempo,U2_gamma07, c="magenta", label="piso 2", linewidth=0.7)
plt.plot(tiempo,U3_gamma07, c="c", label="piso 3", linewidth=0.7 )
plt.xlabel("tiempo")
plt.ylabel("Amplitud")
plt.grid()
plt.savefig("gamma_alto.pdf")
plt.close()

plt.figure()
plt.plot(tiempo,U1_1, c="royalblue", label="primer piso", linewidth=0.7)
plt.plot(tiempo,U2_1, c="lawngreen", label="segundo piso", linewidth=0.7)
plt.plot(tiempo,U3_1, c="tomato", label="tercer piso", linewidth=0.7)
plt.xlabel("tiempo")
plt.ylabel("desplazamiento horizontal")
plt.title("Desplazamiento hotizontal vs. Tiempo omega= 2")
plt.legend()
plt.grid()
plt.savefig("Desplazamiento1.pdf")
plt.close()

plt.figure()
plt.plot(tiempo,U1_2, c="royalblue", label="primer piso", linewidth=0.7)
plt.plot(tiempo,U2_2, c="lawngreen", label="segundo piso", linewidth=0.7)
plt.plot(tiempo,U3_2, c="tomato", label="tercer piso", linewidth=0.7)
plt.xlabel("tiempo")
plt.ylabel("desplazamiento horizontal")
plt.title("Desplazamiento hotizontal vs. Tiempo omega= 4")
plt.legend()
plt.grid()
plt.savefig("Desplazamiento2.pdf")
plt.close()
